version: '3.8'

services:
  bakesale.api:
    image: bakesale.api
    build:
      context: .
      dockerfile: BakeSale.API/Dockerfile
    ports:
      - "5788:8080"   
      - "5788:8081"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CharitySaleDB;Username=postgres;Password=password
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: CharitySaleDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
